CREATE INDEX IF NOT EXISTS "AcademicYear_isCurrent_startDate_idx" ON "AcademicYear"("isCurrent", "startDate");
CREATE INDEX IF NOT EXISTS "AcademicYear_startDate_endDate_idx" ON "AcademicYear"("startDate", "endDate");
CREATE INDEX IF NOT EXISTS "Stage_order_idx" ON "Stage"("order");
CREATE INDEX IF NOT EXISTS "Grade_stageId_order_idx" ON "Grade"("stageId", "order");
CREATE INDEX IF NOT EXISTS "Section_gradeId_name_idx" ON "Section"("gradeId", "name");
CREATE INDEX IF NOT EXISTS "Student_status_deletedAt_idx" ON "Student"("status", "deletedAt");
CREATE INDEX IF NOT EXISTS "Student_enrollmentDate_idx" ON "Student"("enrollmentDate");
CREATE INDEX IF NOT EXISTS "Enrollment_academicYearId_sectionId_status_idx" ON "Enrollment"("academicYearId", "sectionId", "status");
CREATE INDEX IF NOT EXISTS "Enrollment_studentId_status_idx" ON "Enrollment"("studentId", "status");
CREATE INDEX IF NOT EXISTS "Subject_gradeId_name_idx" ON "Subject"("gradeId", "name");
CREATE INDEX IF NOT EXISTS "TeacherSubject_subjectId_employeeId_idx" ON "TeacherSubject"("subjectId", "employeeId");
CREATE INDEX IF NOT EXISTS "Invoice_studentId_status_idx" ON "Invoice"("studentId", "status");
CREATE INDEX IF NOT EXISTS "Invoice_studentId_createdAt_idx" ON "Invoice"("studentId", "createdAt");
CREATE INDEX IF NOT EXISTS "Invoice_status_dueDate_idx" ON "Invoice"("status", "dueDate");
CREATE INDEX IF NOT EXISTS "Invoice_status_createdAt_idx" ON "Invoice"("status", "createdAt");
CREATE INDEX IF NOT EXISTS "Payment_invoiceId_paidAt_idx" ON "Payment"("invoiceId", "paidAt");
CREATE INDEX IF NOT EXISTS "Payment_status_paidAt_idx" ON "Payment"("status", "paidAt");
CREATE INDEX IF NOT EXISTS "Payment_method_paidAt_idx" ON "Payment"("method", "paidAt");
CREATE INDEX IF NOT EXISTS "Payment_receivedBy_paidAt_idx" ON "Payment"("receivedBy", "paidAt");
CREATE INDEX IF NOT EXISTS "FeeStructure_academicYearId_gradeId_category_idx" ON "FeeStructure"("academicYearId", "gradeId", "category");
CREATE INDEX IF NOT EXISTS "FeeStructure_isRequired_category_idx" ON "FeeStructure"("isRequired", "category");
CREATE INDEX IF NOT EXISTS "Expense_status_date_idx" ON "Expense"("status", "date");
CREATE INDEX IF NOT EXISTS "Expense_category_date_idx" ON "Expense"("category", "date");
